"""
会员 Bot 配置样例。

复制本文件中的结构到 settings.py，再填入真实配置。
不要把真实 Token、管理员 ID 和收款地址提交到公开仓库。
"""

# Bot 配置
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
ADMIN_USER_IDS = [123456789]

# 数据库配置
USER_DATABASE_PATH = "/www/wwwroot/byvip/database/users.db"
COLLECTOR_DATABASE_PATH = "/www/wwwroot/bycjbot/database/post.db"

# 频道配置
MAIN_CHANNEL_ID = -1000000000000
VIDEO_VERIFY_CHANNEL_ID = -1000000000000

# 客服群配置
CUSTOMER_SERVICE_CHAT_ID = -1000000000000
ANNOUNCEMENT_TOPIC_ID = 123

# 监听群配置
MONITORED_GROUP_ID = -1000000000000

# VIP 配置
VIP_PRICE_USDT = 100
VIP_DURATION_DAYS = 360
DEFAULT_CREDITS = 5
REFERRAL_CREDITS = 5
REFERRAL_BONUS_BALANCE = 10
CREDITS_PER_VIDEO = 1

# USDT 支付配置
USDT_WALLET_ADDRESS = "YOUR_TRC20_USDT_ADDRESS"
PAYMENT_CHECK_INTERVAL_SECONDS = 15
PAYMENT_TIMEOUT_MINUTES = 10
VERIFICATION_AMOUNT_MIN = 99.00
VERIFICATION_AMOUNT_MAX = 99.99

# 订阅推送配置
SUBSCRIPTION_PUSH_ENABLED = True
SUBSCRIPTION_PUSH_INTERVAL_MINUTES = 2
SUBSCRIPTION_SEARCH_HOURS = 1
NORMAL_MAX_SUBSCRIPTIONS = 1
VIP_MAX_SUBSCRIPTIONS = 5

# 白名单配置
WHITELIST_CHATS = [
    CUSTOMER_SERVICE_CHAT_ID,
    MONITORED_GROUP_ID,
    MAIN_CHANNEL_ID,
    VIDEO_VERIFY_CHANNEL_ID,
]

# 搜索配置
SEARCH_RESULTS_PER_PAGE = 10
SEARCH_MAX_RESULTS = 50
HEIGHT_TOLERANCE = 4
WEIGHT_TOLERANCE = 4
AGE_TOLERANCE = 2

# 其他配置
BOT_USERNAME = "your_bot_username"
